service: lambda-functions-experiments

provider:
  name: aws
  runtime: python3.7
  stage: development
  region: eu-central-1
  lambdaHashingVersion: 20201221

package:
  patterns:
    - "!node_modules/**"
    - "!.venv/**"
    - "!pytest_cache/**"
    - "!tests"

functions:
  users:
    handler: handlers/main.handler
    description: 'Simple handler that access a Postgres database.'
    memorySize: 128
    timeout: 15

plugins:
  - serverless-python-requirements
  - serverless-pseudo-parameters
