name: CI/CD Pipeline

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  development-deployment:
    name: Development Deployment
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    environment:
      name: Development

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install Pipenv
        run: sudo pip install pipenv

      - name: Install Serverless Dependencies
        run: npm install

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
          role-to-assume: ${{ secrets.AWS_ROLE_LAMBDA_DEPLOYMENT }}
          role-duration-seconds: 900
          role-session-name: ServerlessDeploymentSession
          role-skip-session-tagging: true

      - name: Serverless Deployment
        run: npm run deploy:development
